name: Build and Deploy Web Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Convert Audio to OGG
      run: |
        ffmpeg -i UNITY.mp3 UNITY.ogg
        
    - name: Install dependencies
      run: |
        pip install pygame pygbag
        
    - name: Build web version
      run: |
        python -m pygbag --width 800 --height 600 --app_name "Ball-Simulator" .
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
